### ISSUE TITLE
Questions about the BQ branch

### ISSUE THREAD

**Issue by ron819** [JohnLewisandPartners/custom-airflow-plugins#1]
1. Is it possible to see example ?
2. does it support path to SQL file or only hard codded query?
3. does it support standard SQL?

**Comment by antxxxx** [comment]
1. I have updated the code with an example in the comments - does this cover your needs?
2. I have updated the version so it can use a path to sql file as well as a query string. Let me know if it works for you as the documentation on using templated files seemed lacking when I tried it
3. There is a use_legacy_sql param that controls which dialect to use

**Comment by antxxxx** [comment]
For 2 I have put some comments in to indicate how to use a .sql file. You need to ensure that you set template_searchpath at the DAG level to indicate the folder where the .sql file is

**Comment by ron819** [comment]
@antxxxx 
got an unexpected keyword argument 'use_legacy_sql'

```
check_osc_orders_op = BranchBQOperator(
    task_id='check_orders',
    sql = check_orders_query_new,
    use_legacy_sql = False,
    bigquery_conn_id=CONNECTION_ID,
	pass_task = 'skip_task',
	fail_task = 'post_msg',
    dag=dag
)	
```

**Comment by antxxxx** [comment]
The version in master only works on airflow 1.10. There is a branch called airfow_1.9 that works on airflow 1.9 (I had to backport the latest BigQuery hook to get it to work in 1.9).   

I have updated the readme to indicate which branch to use

The pass and fail tasks should be the task_ids. I have updated the comments to indicate this

**Comment by ron819** [comment]
@antxxxx 
OK used the 1.9 version
Works like a charm!

Really hope that you will submit this op to Airflow master.

**Comment by antxxxx** [comment]
Great news.   

I do plan to submit this back to the main airflow repo when I get the chance
